### ISSUE TITLE
Replace Knex

### ISSUE THREAD

**Issue by NullEnt1ty** [NullEnt1ty/serienabend-shef#3]
Knex does generally does a good job at building queries. It's a mature project and supports a lot of DBMS drivers.

One thing that annoys me though is the lack of _good_ TypeScript support. When building simple queries it's usually fine, but when building more complex queries that use aggregation and/or aliases, Knex quickly gets confused and infers the wrong type, forcing the developer to resort to type assertion. This works but it's not great DX and can lead to bugs when refactoring the query later on without updating the asserted type.

**Comment by NullEnt1ty** [comment]
While trying to migrate to Bun, I encountered a problem with Knex when bundling the project:

```
bun build --outdir ./dist --target bun src/app.ts
7 |     return require('better-sqlite3');
                       ^
error: Could not resolve: "better-sqlite3". Maybe you need to "bun install"?
    at /Users/dominique/projects/serienabend-shef/node_modules/knex/lib/dialects/better-sqlite3/index.js:7:20

42 |     return require('sqlite3');
                        ^
error: Could not resolve: "sqlite3". Maybe you need to "bun install"?
    at /Users/dominique/projects/serienabend-shef/node_modules/knex/lib/dialects/sqlite3/index.js:42:20

44 |     return require('pg');
                        ^
error: Could not resolve: "pg". Maybe you need to "bun install"?
    at /Users/dominique/projects/serienabend-shef/node_modules/knex/lib/dialects/redshift/index.js:44:20

63 |     return require('pg');
                        ^
error: Could not resolve: "pg". Maybe you need to "bun install"?
    at /Users/dominique/projects/serienabend-shef/node_modules/knex/lib/dialects/postgres/index.js:63:20

192 |       : require('pg-query-stream');
                      ^
error: Could not resolve: "pg-query-stream". Maybe you need to "bun install"?
    at /Users/dominique/projects/serienabend-shef/node_modules/knex/lib/dialects/postgres/index.js:192:17

24 |     return require('mysql');
                        ^
error: Could not resolve: "mysql". Maybe you need to "bun install"?
    at /Users/dominique/projects/serienabend-shef/node_modules/knex/lib/dialects/mysql/index.js:24:20

13 |     return require('pg').native;
                        ^
error: Could not resolve: "pg". Maybe you need to "bun install"?
    at /Users/dominique/projects/serienabend-shef/node_modules/knex/lib/dialects/pgnative/index.js:13:20

44 |     const oracledb = require('oracledb');
                                  ^
error: Could not resolve: "oracledb". Maybe you need to "bun install"?
    at /Users/dominique/projects/serienabend-shef/node_modules/knex/lib/dialects/oracledb/index.js:44:30

94 |     const tds = require('tedious');
                             ^
error: Could not resolve: "tedious". Maybe you need to "bun install"?
    at /Users/dominique/projects/serienabend-shef/node_modules/knex/lib/dialects/mssql/index.js:94:25
```

Bun cannot resolve those imports because they're not installed. Haven't looked at the source code of Knex but I'm pretty sure that it requires these libraries conditionally as starting the application with `bun src/app.ts` works fine.
